name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Escribir serviceAccount.json desde secret
        run: |
          mkdir -p src/main/resources/firebase
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > src/main/resources/firebase/serviceAccount.json

      - name: Run tests
        run: ./gradlew test
